[package]
name = "gbrust"
version = "0.1.0"
authors = ["h-izu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.19.1"
